// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonSearchesListingsController from "./button_searches_listings_controller"
application.register("button-searches-listings", ButtonSearchesListingsController)

import ButtonYesNoController from "./button_yes_no_controller"
application.register("button-yes-no", ButtonYesNoController)

import ClearChatFormController from "./clear_chat_form_controller"
application.register("clear-chat-form", ClearChatFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MatchSubscriptionController from "./match_subscription_controller"
application.register("match-subscription", MatchSubscriptionController)

import OutputController from "./output_controller"
application.register("output", OutputController)

import ProfileToggleController from "./profile_toggle_controller"
application.register("profile-toggle", ProfileToggleController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)
